MCMi460/NSO-RPC

- client/app.py
Went overkill and deleted branch after realizing my mistake, which closed the PR (sorry): https://github.com/MCMi460/NSO-RPC/pull/18
Also going w/ a fresh PR to be safe.
----
**RE**: https://github.com/MCMi460/NSO-RPC/issues/17#issuecomment-1152932321
**Issue**- `i` is `0` on first friend, which sets `j` to `0` (`j = i % 4`)
Therefore `layout.addWidget(overlay)` is not called:
```
if j > 0:
layout.addWidget(overlay)
```
**Fix**? Simply allowing 0 seems to be fine
```
if j >= 0:
layout.addWidget(overlay)
```
> Ensure single friend widget is added

- client/app.py
**What**? Set icon color to light if dark mode
**Why**? Hard to find icon
**Fix**? Added helper method `SystemTrayApp.windowsLightMode()` 🤷‍♂️ -> used in check similar to MacOS
This would make dark mode better for GUI:
> set correct windows systray icon color

- client/api/__init__.py
**What**? [Token failing to refresh at two hour mark](https://github.com/MCMi460/NSO-RPC/issues/21)
**Why**? https://github.com/MCMi460/NSO-RPC/issues/21#issuecomment-1159227333
**Fix**? Generate new token before logging in again
**Note**: It sounds like more work should be done [around `access_token` vs. `id_token`, and `request_id`,](https://github.com/MCMi460/NSO-RPC/issues/21#issuecomment-1159227333) per @[samuelthomas2774](https://github.com/samuelthomas2774) on #21 to keep things kosher, but this is working for me...
----
**Edit**: So far so good running built executable. No crashes/still logged-in, clicking through the app menus hours later (#12) works fine, etc.
```
TotalHours        : 24.8919162690278
```
> Add API.refreshAccessToken() for use in API.updateLogin()

- client/app.py
- client/cli.py
Windows allows you to move/store a users subfolders, such as Documents in a different location, This could be another hard drive to make reinstalling not as tedious. 
The below code however assumes that these are only stored in the default location, such as `C:\Users\Username`.
```py
os.path.expanduser('~/Documents/NSO-RPC')
```
This commit resolves this by wrapping the path in a `getAppPath()` function, and attempting to get the path from Windows and falling back on the above method if it fails or not on windows.
Attempting to use the Default location can cause strange behavioural issues in windows, depending on how the locations were setup. as well as how the application handles it.
---
I also believe this could have affected #10 however this issue is stale and I haven't tested Windows …
> Windows fix for Documents folder not being in the default location.

- client/api/__init__.py
Apple seems to have changed the HTML for the version, where it has two spaces now before the version number. This may be a bug on their side however it does break our current version regex, so this adds a fallback to handle this extra space if the first method fails. 
Below is the snippet showing the html
```html
<div class="l-column small-12 medium-3 large-4 small-valign-top whats-new__latest">
<div class="l-row">
<time data-test-we-datetime datetime="2022-12-01T00:00:00.000Z" aria-label="December 1, 2022" class="" >Dec 1, 2022</time>
<p class="l-column small-6 medium-12 whats-new__latest__version">Version  2.4.0</p>
</div>
</div>
```
> Hotfix apple version regex

- client/requirements.txt
**Update: This has been fixed via: https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/534 and was in fact an issue with PyInstaller, I've done the correct fix and replaced the commit.**
---
Requests has released [v2.28.2](https://github.com/psf/requests/releases/tag/v2.28.2) that added support for charset_normalizer 3.x, However it seems to be causing build issues when the application is built and also trying to use chardet (An alternative to charset_normalizer), the application is meant to detect and decide what one to use, however failing with PyInstaller.
~~Forcing charset_normalizer to 2.x seems to fix the issue, however this may only be a temporary change.~~
Note: The environment that triggers this issue seems semi-random. However I was able to replicate it on a fresh …
> Pin pyinstaller-hooks-contrib to fix Requests v2.28.2 dependency 

- client/requirements.txt
Fix #60 
Ubuntu seems to be using their own build of python, aswell as Python3-PyQt5, This seems to cause weird behaviour, most likely due to weird edge cases and ubuntu's version of PyQt5 seems to expect qtpy to exist due to it being an abstraction layer.
Adding this requirement fixes Ubuntu 22.04 and does not affect the windows build and both have been tested working with this change.
> Add "qtpy" to requirements.txt

- scripts/install.sh
python3-pip is not installed by default with newer versions of Debian/Ubuntu out of the box.
This PR installs python3-pip only **if the user does not already have a working pip environment**.
This should in theory help prevent breaking custom pip local user installations.
> python3-pip is required on newer versions of ubuntu

- client/requirements.txt
The following issue with PR #59 showed up again, I tried updating the hooks but the issue still occurs, Their seemed to mainly be an issue with MacOS and the universal2 builds.
Locking `charset_normalizer` to v2 fixes this and hopefully by locking these three packages stop this occurring again for awhile, but a better fix may be needed in the future.
> Fix and lock the packages for building NSO-RPC

- .github/workflows/actions.yml
- scripts/linux.sh
<ins>**This needs #68 or the macOS build will be broken!**</ins>
---
This PR adds auto building for NSO-RPC via GitHub Actions, I've tested all 3 builds and they seem to work correctly, however NSO-RPC's mac build still needs tested on an m1 mac, but I believe it should work without an issue due to Rosetta 2.
This does not currently set the release notes, however it does not set these and only adds the files as their build, so that is currently needed to be done manually.
This also changes how NSO-RPC is build on mac slightly. This changes the original `mac.zip` to `mac-portable.zip`, as I've added an installable version of NSO-RPC via productbuild and that's known as `mac-installer.zip`, More details about my reasoning below.
---
This is mainly useful because for #66, this PR isn't …
> Add Github Actions

- client/app.py
This fixes an issue with #66 where if you were running the portable build inside the downloads Folder, the autostart wouldn't work due to MacOS security settings around untrusted apps in the downloads folder.
This PR assumes that only the Downloads folder can trigger a `/private/var/folders`  working directory, so we rewrite the application directory to be the users download folder to repair auto restart functionality.
> [Macos] Fix autostart when running in Downloads folder

- client/api/__init__.py
Recently their was a change that broke Nintendo f-generation, This has mostly been fixed however theirs still some downtime issues with imink, that may need extra attempts before failing.
However this PR adds the na_id that is recommended to be send now for the new f-generation, and I believe I've implemented it correctly, These changes are noted here: https://github.com/samuelthomas2774/nxapi/discussions/10#discussioncomment-5995498
Note, NSO-RPC does in fact currently work again, however this is more future proofing.
I also noticed when doing this that hashMethod got changed awhile ago, and its meant to be hash_method, however the old way was still supported, so i decided to update the header.
Edit: I remade the PR because I noticed a issue with the previous one, and i had to rewrite …
> [Fixed PR] Add na_id and fix hash_method header.

- client/app.py
- client/cli.py
If you are running Discord as administrator, NSO-RPC will fail to connect to the discord IPC pipe due to windows permissions.
I attempted to catch the `'[WinError 5] Access is denied'` exception at [client/cli.py#L50-L56](https://github.com/MCMi460/NSO-RPC/blob/main/client/cli.py#L50-L56), as it returns an IOError exception, however I had multiple timing and scope(?) issues around that, even trying to add handler and extra stuff around a simple boolean had consistency issues, reporting not connected to discord, then afterwards saying we are fine etc.
This solution's main issue is that its assuming on windows, the only reason for NSO-RPC to have issues connecting to discord is because Discord is running with Admin privileges.
**Note: This will give a false positive telling the user to try …
> Add run as admin suggestion for Windows

- client/app.py
This fixes both the icon missing from the system try if launched via the service file, aswell as fixes the app name so its "NSO-RPC" instead of "app.py"
> Fix System tray support on Linux

- .github/workflows/actions.yml
- scripts/macos-universal2/build.sh
- scripts/macos-universal2/debloat-qt.py
- scripts/macos-universal2/prep-PyQt.sh
This PR adds a working version of Universal2 for macOS, Below are some things to note about this
1) We are manually installing Python 3.10.11(universal2 build) as theirs no easy way to FORCE a universal2 install via the python GitHub action.
2) We are running a python script on the final build of universal2 to remove some bloat that is bundled into it to save space before compressing and packaging it.
3) The universal2 build is only guaranteed to be this small due to GitHub Actions  and how are are building it, Locally building will have wildly different size results, so keep that in mind.
Lastly due to the nature of this Universal2 build, It could start randomly failing to build and will need to get small tweaks now and again.
> Add Universal2 MacOS Support

- .github/workflows/actions.yml
- scripts/build.bat
- scripts/macos-universal2/prep-PyQt.sh
Updates Python from 3.10 to 3.11, as 3.10 is only receiving bug fixes.
- Fixes a typo I missed with the build.bat script due to the path being wrong 
- Update PyInstaller due to : https://github.com/pyinstaller/pyinstaller/issues/7692
An unintended feature of this PR is that the universal2 build seems to be around 20MB~ Bigger, rather than try and figure it out, i think its better to take the slightly larger size for an up-to-date python.
> Python 3.10.11 -> 3.11.4

- scripts/build.sh
I don't believe this will fix the issue from #91, as I believe this is always going to happen for m1 users not using the universal2 build in the future due to the differences on how Qt6 is bundled with the app.
However the issue with the x64 build including arm64/universal2 build is believed to be caused by #90, So this just prevents arm64 being included on the x64 build that uses a different build.sh file.
> Force x86_64 on non-universal2 builds

- client/api/__init__.py
This previous code is really easy to break on MacOS, and didn't behave consistently depending on the folder its in. Such as the following
1. It does not work correctly when stored in the downloads folder
2. Incorrect path when executing NSO-RPC app directly via command line, such as
`./client/dist/NSO-RPC.app/Contents/MacOS/NSO-RPC`
This code now works no matter where NSO-RPC is located, and is a little easier to read than the previous solution
> Fix Portable mode for MacOS

- client/api/__init__.py
Rewrites getVersion for NSO-RPC getting the version from app store, because sometimes when the request fails, the app errors due to r is not defined.
This just makes sure that r is valid, and also logging what the errors were for better diagnostics as well as fixes the fallback of the text prompt.
___
Image from the discord showing the issue in question.
> Rewrite the getVersion code to catch errors and catch request failing.

- client/api/__init__.py
- client/app.py
- scripts/install.sh
- scripts/linux.sh
This PR adds a couple of fixes, however some issues still aren't addressed with this PR.
- Although this adds overrideVersion, its not 100% correctly implemented, and will cause NSO-RPC to crash on first token generation with the override, launching the app again works as intended.
_Note: This also still requires editing a file and does not have the alternative solution we discussed to prevent f-token version issues in the future._
- Now when you select a user and confirm, NSO-RPC will restart itself.
- Added support for venv that's enabled by default if using the the linux.sh & install.sh script, this is disabled via an argument and more have been added to support better customization
```
-r / --repo : What github account to use, Such as HotaruBlaze or MCMi460
-b / --branch : What github …
```
> Multiple small tweaks and fixes

- .github/workflows/actions.yml
- client/_version.py
- client/api/__init__.py
- scripts/build.sh
- scripts/macos-universal2/build.sh
- scripts/tests/macos_test.sh
This PR Merges PR's #145 #142 #139 to be a cleaner initial merge.
This also resolves issues: #146 #140 #144
[[API] Handle imink API being down](https://github.com/MCMi460/NSO-RPC/commit/e5109a604f9acf0dd872e14b48f1bfbfae2cb512): Actually print an error when imink is down, instead of the previous timestamp error.
[[API] Fix getVersion discrepency causing an error](https://github.com/MCMi460/NSO-RPC/commit/4a14b101efd4ef10b09372538f7f10c1ec32f8b9): Theirs a mismatch between the regex's in app.py and the cli __init__, This replaces then with a function dedicated to the regex for both sides.
[[Github] Update actions and cleanup job ordering](https://github.com/MCMi460/NSO-RPC/commit/9415c361d1075ceb3c0bce2dfc99c8e0740e0a96): Updates the action images, Also reorganized the jobs matrix to be …
> Multiple bugfixes and tweaks around Github actions.

- client/api/__init__.py
- client/app.py
This removes the old system of scraping the version of NSO from the apple store, and instead use the version that our f-api generation is currently using.
This should in theory prevent ANY more issues with tokens being invalid when nintendo pushes an update before F-API can update.
https://api.imink.app/config
```json
{"nso_version":"2.10.0"}
```
---
I also moved a couple of helper funcs from app.py to api/__init__.py.
> [Feat] Replace dependency on Apple with returned version from f-api

- scripts/install.sh
This fixes an issue where we aren't installing pyqt 5/6 in the venv, this causes an issue because then the app cant launch correctly.
This needs to be merged into main as well as development, however shouldn't need a new release.
> [Fix] if using venv, install PyQt inside it

- README.md
- client/api/__init__.py
- client/app.py
I've added a warning to the readme, as its Nintendo took more action and restricted a bunch of Nintendo services, and theirs no ETA for it to be fixed. **_This should be merged to Development and main._**
This PR implements the following...
[[Bugfix] Update windows Imports when running script directly.](https://github.com/MCMi460/NSO-RPC/commit/951373aa9f4a3942857e98ab8328b717d53c8694)
[[Tweak] Clarify F Calculation API error message.](https://github.com/MCMi460/NSO-RPC/commit/459fa0bfb55c3a09b35225680c8e19a9cda1122f)
[[Docs] Update readme about the current issue with NSO](https://github.com/MCMi460/NSO-RPC/commit/1ebd186610e93c1654450b7f919fae1e01ce2bea)
> Add Disclaimer to Readme and small tweaks
